# Generated by Django 6.0.3 on 2026-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='file',
        ),
        migrations.AddField(
            model_name='comments',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
